import * as Monaco from "monaco-editor/esm/vs/editor/editor.api";

export const defaultMainEditorOptions: Monaco.editor.IStandaloneEditorConstructionOptions =
  {
    fontFamily: "Cascadia Mono",
    fontSize: 14,
    lineHeight: 24,
    minimap: { enabled: false },
    smoothScrolling: true,
    scrollBeyondLastLine: true,
    scrollbar: {
      vertical: "auto",
      horizontal: "auto",
      useShadows: false,
      verticalScrollbarSize: 8,
      horizontalScrollbarSize: 8,
      verticalSliderSize: 8,
      horizontalSliderSize: 8,
    },
    lineNumbersMinChars: 3,
    lineDecorationsWidth: 0,
    lineNumbers: "on",
    wordWrap: "on",
    wrappingIndent: "deepIndent",
    suggestOnTriggerCharacters: true,
    quickSuggestions: {
      other: true,
      comments: true,
      strings: true,
    },
    snippetSuggestions: "inline",
    acceptSuggestionOnEnter: "off",
    tabCompletion: "on",
    wordBasedSuggestions: "allDocuments",
    suggestSelection: "first",
    parameterHints: {
      enabled: true,
    },
    suggest: {
      localityBonus: true,
      snippetsPreventQuickSuggestions: false,
      showIcons: true,
      showStatusBar: true,
      preview: true,
      showMethods: true,
      showFunctions: true,
      showConstructors: true,
      showDeprecated: false,
      matchOnWordStartOnly: false,
      filterGraceful: true,
      showWords: true,
      showSnippets: true,
      showInlineDetails: true,
      shareSuggestSelections: true,
      insertMode: "insert",
    },
    suggestLineHeight: 24,
  };

export const defaultInputOutputEditorOptions: Monaco.editor.IStandaloneEditorConstructionOptions =
  {
    fontFamily: "Cascadia Mono",
    fontSize: 14,
    lineHeight: 24,
    renderLineHighlight: "none",
    hideCursorInOverviewRuler: true,
    overviewRulerBorder: false,
    scrollBeyondLastLine: false,
    wordWrap: "on",
    minimap: { enabled: false },
    lineNumbersMinChars: 3,
    lineDecorationsWidth: 0,
    scrollbar: {
      vertical: "auto",
      horizontal: "auto",
      useShadows: false,
      verticalScrollbarSize: 8,
      horizontalScrollbarSize: 8,
      verticalSliderSize: 8,
      horizontalSliderSize: 8,
    },
  };
